### ISSUE TITLE
Affinity Designer doesn't open in latest version - 19

### ISSUE THREAD

**Issue by fewerjunk** [bjango/Color-Creator#2]
Tried opening.  It says incompatible.

![014D8BA2-18FF-40B0-998D-5F450580A8CB_4_5005_c](https://user-images.githubusercontent.com/70761456/107121289-73849400-6846-11eb-9926-193b27f19425.jpeg)

**Comment by marcedwards** [comment]
Hi! Please try again now with the latest file. I’ve just resaved using Affinity Designer 1.8. I have been able to open it with Affinity Designer 1.9 on Mac.

**Comment by fewerjunk** [comment]
I’m game.  Where is it?

**Comment by fewerjunk** [comment]
Found it.  Nevermind.
